//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.25 at 04:38:05 PM CET 
//

package org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_resourceallocationsettingdata;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.dmtf.schemas.ovf.envelope._1.RASDType;
import org.dmtf.schemas.wbem.wscim._1.common.CimBoolean;
import org.dmtf.schemas.wbem.wscim._1.common.CimString;
import org.dmtf.schemas.wbem.wscim._1.common.CimUnsignedInt;
import org.dmtf.schemas.wbem.wscim._1.common.CimUnsignedLong;
import org.dmtf.schemas.wbem.wscim._1.common.CimUnsignedShort;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for CIM_ResourceAllocationSettingData_Type complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;CIM_ResourceAllocationSettingData_Type&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Caption&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Description&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}InstanceId&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}ResourceType&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}OtherResourceType&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}ResourceSubType&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}PoolID&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}ConsumerVisibility&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}HostResource&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}AllocationUnits&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}VirtualQuantity&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Reservation&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Limit&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Weight&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}AutomaticAllocation&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}AutomaticDeallocation&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Parent&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Connection&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Address&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}MappingBehavior&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}AddressOnParent&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}BusNumber&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;any/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIM_ResourceAllocationSettingData_Type", propOrder = {"caption", "description",
    "instanceId", "resourceType", "otherResourceType", "resourceSubType", "poolID",
    "consumerVisibility", "hostResource", "allocationUnits", "virtualQuantity", "reservation",
    "limit", "weight", "automaticAllocation", "automaticDeallocation", "parent", "connection",
    "address", "mappingBehavior", "addressOnParent", "busNumber", "any"})
@XmlSeeAlso( {RASDType.class})
public class CIMResourceAllocationSettingDataType
{

    @XmlElement(name = "Caption", nillable = true)
    protected List<CimString> caption;

    @XmlElement(name = "Description", nillable = true)
    protected List<CimString> description;

    @XmlElement(name = "InstanceId", nillable = true)
    protected CimString instanceId;

    @XmlElement(name = "ResourceType", nillable = true)
    protected ResourceType resourceType;

    @XmlElement(name = "OtherResourceType", nillable = true)
    protected CimString otherResourceType;

    @XmlElement(name = "ResourceSubType", nillable = true)
    protected CimString resourceSubType;

    @XmlElement(name = "PoolID", nillable = true)
    protected CimString poolID;

    @XmlElement(name = "ConsumerVisibility", nillable = true)
    protected ConsumerVisibility consumerVisibility;

    @XmlElement(name = "HostResource", nillable = true)
    protected List<Object> hostResource;

    @XmlElement(name = "AllocationUnits", nillable = true)
    protected CimString allocationUnits;

    @XmlElement(name = "VirtualQuantity", nillable = true)
    protected CimUnsignedLong virtualQuantity;

    @XmlElement(name = "Reservation", nillable = true)
    protected CimUnsignedLong reservation;

    @XmlElement(name = "Limit", nillable = true)
    protected CimUnsignedLong limit;

    @XmlElement(name = "Weight", nillable = true)
    protected CimUnsignedInt weight;

    @XmlElement(name = "AutomaticAllocation", nillable = true)
    protected CimBoolean automaticAllocation;

    @XmlElement(name = "AutomaticDeallocation", nillable = true)
    protected CimBoolean automaticDeallocation;

    @XmlElement(name = "Parent", nillable = true)
    protected CimString parent;

    @XmlElement(name = "Connection", nillable = true)
    protected List<CimString> connection;

    @XmlElement(name = "Address", nillable = true)
    protected CimString address;

    @XmlElement(name = "MappingBehavior", nillable = true)
    protected MappingBehavior mappingBehavior;

    @XmlElement(name = "AddressOnParent", nillable = true)
    protected CimString addressOnParent;

    @XmlElement(name = "BusNumber", nillable = true)
    protected CimUnsignedShort busNumber;

    @XmlAnyElement(lax = true)
    protected List<Object> any;

    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the caption property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the caption property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCaption().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CimString }
     */
    public List<CimString> getCaption()
    {
        if (caption == null)
        {
            caption = new ArrayList<CimString>();
        }
        return this.caption;
    }

    /**
     * Gets the value of the description property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the description property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDescription().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CimString }
     */
    public List<CimString> getDescription()
    {
        if (description == null)
        {
            description = new ArrayList<CimString>();
        }
        return this.description;
    }

    /**
     * Gets the value of the instanceId property.
     * 
     * @return possible object is {@link CimString }
     */
    public CimString getInstanceId()
    {
        return instanceId;
    }

    /**
     * Sets the value of the instanceId property.
     * 
     * @param value allowed object is {@link CimString }
     */
    public void setInstanceId(CimString value)
    {
        this.instanceId = value;
    }

    /**
     * Gets the value of the resourceType property.
     * 
     * @return possible object is {@link ResourceType }
     */
    public ResourceType getResourceType()
    {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value allowed object is {@link ResourceType }
     */
    public void setResourceType(ResourceType value)
    {
        this.resourceType = value;
    }

    /**
     * Gets the value of the otherResourceType property.
     * 
     * @return possible object is {@link CimString }
     */
    public CimString getOtherResourceType()
    {
        return otherResourceType;
    }

    /**
     * Sets the value of the otherResourceType property.
     * 
     * @param value allowed object is {@link CimString }
     */
    public void setOtherResourceType(CimString value)
    {
        this.otherResourceType = value;
    }

    /**
     * Gets the value of the resourceSubType property.
     * 
     * @return possible object is {@link CimString }
     */
    public CimString getResourceSubType()
    {
        return resourceSubType;
    }

    /**
     * Sets the value of the resourceSubType property.
     * 
     * @param value allowed object is {@link CimString }
     */
    public void setResourceSubType(CimString value)
    {
        this.resourceSubType = value;
    }

    /**
     * Gets the value of the poolID property.
     * 
     * @return possible object is {@link CimString }
     */
    public CimString getPoolID()
    {
        return poolID;
    }

    /**
     * Sets the value of the poolID property.
     * 
     * @param value allowed object is {@link CimString }
     */
    public void setPoolID(CimString value)
    {
        this.poolID = value;
    }

    /**
     * Gets the value of the consumerVisibility property.
     * 
     * @return possible object is {@link ConsumerVisibility }
     */
    public ConsumerVisibility getConsumerVisibility()
    {
        return consumerVisibility;
    }

    /**
     * Sets the value of the consumerVisibility property.
     * 
     * @param value allowed object is {@link ConsumerVisibility }
     */
    public void setConsumerVisibility(ConsumerVisibility value)
    {
        this.consumerVisibility = value;
    }

    /**
     * Gets the value of the hostResource property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the hostResource property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getHostResource().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Object }
     */
    public List<Object> getHostResource()
    {
        if (hostResource == null)
        {
            hostResource = new ArrayList<Object>();
        }
        return this.hostResource;
    }

    /**
     * Gets the value of the allocationUnits property.
     * 
     * @return possible object is {@link CimString }
     */
    public CimString getAllocationUnits()
    {
        return allocationUnits;
    }

    /**
     * Sets the value of the allocationUnits property.
     * 
     * @param value allowed object is {@link CimString }
     */
    public void setAllocationUnits(CimString value)
    {
        this.allocationUnits = value;
    }

    /**
     * Gets the value of the virtualQuantity property.
     * 
     * @return possible object is {@link CimUnsignedLong }
     */
    public CimUnsignedLong getVirtualQuantity()
    {
        return virtualQuantity;
    }

    /**
     * Sets the value of the virtualQuantity property.
     * 
     * @param value allowed object is {@link CimUnsignedLong }
     */
    public void setVirtualQuantity(CimUnsignedLong value)
    {
        this.virtualQuantity = value;
    }

    /**
     * Gets the value of the reservation property.
     * 
     * @return possible object is {@link CimUnsignedLong }
     */
    public CimUnsignedLong getReservation()
    {
        return reservation;
    }

    /**
     * Sets the value of the reservation property.
     * 
     * @param value allowed object is {@link CimUnsignedLong }
     */
    public void setReservation(CimUnsignedLong value)
    {
        this.reservation = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return possible object is {@link CimUnsignedLong }
     */
    public CimUnsignedLong getLimit()
    {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value allowed object is {@link CimUnsignedLong }
     */
    public void setLimit(CimUnsignedLong value)
    {
        this.limit = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return possible object is {@link CimUnsignedInt }
     */
    public CimUnsignedInt getWeight()
    {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value allowed object is {@link CimUnsignedInt }
     */
    public void setWeight(CimUnsignedInt value)
    {
        this.weight = value;
    }

    /**
     * Gets the value of the automaticAllocation property.
     * 
     * @return possible object is {@link CimBoolean }
     */
    public CimBoolean getAutomaticAllocation()
    {
        return automaticAllocation;
    }

    /**
     * Sets the value of the automaticAllocation property.
     * 
     * @param value allowed object is {@link CimBoolean }
     */
    public void setAutomaticAllocation(CimBoolean value)
    {
        this.automaticAllocation = value;
    }

    /**
     * Gets the value of the automaticDeallocation property.
     * 
     * @return possible object is {@link CimBoolean }
     */
    public CimBoolean getAutomaticDeallocation()
    {
        return automaticDeallocation;
    }

    /**
     * Sets the value of the automaticDeallocation property.
     * 
     * @param value allowed object is {@link CimBoolean }
     */
    public void setAutomaticDeallocation(CimBoolean value)
    {
        this.automaticDeallocation = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return possible object is {@link CimString }
     */
    public CimString getParent()
    {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value allowed object is {@link CimString }
     */
    public void setParent(CimString value)
    {
        this.parent = value;
    }

    /**
     * Gets the value of the connection property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the connection property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getConnection().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CimString }
     */
    public List<CimString> getConnection()
    {
        if (connection == null)
        {
            connection = new ArrayList<CimString>();
        }
        return this.connection;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return possible object is {@link CimString }
     */
    public CimString getAddress()
    {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value allowed object is {@link CimString }
     */
    public void setAddress(CimString value)
    {
        this.address = value;
    }

    /**
     * Gets the value of the mappingBehavior property.
     * 
     * @return possible object is {@link MappingBehavior }
     */
    public MappingBehavior getMappingBehavior()
    {
        return mappingBehavior;
    }

    /**
     * Sets the value of the mappingBehavior property.
     * 
     * @param value allowed object is {@link MappingBehavior }
     */
    public void setMappingBehavior(MappingBehavior value)
    {
        this.mappingBehavior = value;
    }

    /**
     * Gets the value of the addressOnParent property.
     * 
     * @return possible object is {@link CimString }
     */
    public CimString getAddressOnParent()
    {
        return addressOnParent;
    }

    /**
     * Sets the value of the addressOnParent property.
     * 
     * @param value allowed object is {@link CimString }
     */
    public void setAddressOnParent(CimString value)
    {
        this.addressOnParent = value;
    }

    /**
     * Gets the value of the busNumber property.
     * 
     * @return possible object is {@link CimUnsignedShort }
     */
    public CimUnsignedShort getBusNumber()
    {
        return busNumber;
    }

    /**
     * Sets the value of the busNumber property.
     * 
     * @param value allowed object is {@link CimUnsignedShort }
     */
    public void setBusNumber(CimUnsignedShort value)
    {
        this.busNumber = value;
    }

    /**
     * Gets the value of the any property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the any property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAny().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Element } {@link Object }
     */
    public List<Object> getAny()
    {
        if (any == null)
        {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * <p>
     * the map is keyed by the name of the attribute and the value is the string value of the
     * attribute. the map returned by this method is live, and you can add new attribute by updating
     * the map directly. Because of this design, there's no setter.
     * 
     * @return always non-null
     */
    public Map<QName, String> getOtherAttributes()
    {
        return otherAttributes;
    }

}
