//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.25 at 04:38:05 PM CET 
//

package com.abiquo.ovfindex;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.abiquo.ovfindex package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory
{

    private final static QName _RepositorySpace_QNAME =
        new QName("http://www.abiquo.com/ovfindex", "RepositorySpace");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes
     * for package: com.abiquo.ovfindex
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link OVFPackage }
     */
    public OVFPackage createOVFPackage()
    {
        return new OVFPackage();
    }

    /**
     * Create an instance of {@link RepositorySpace }
     */
    public RepositorySpace createRepositorySpace()
    {
        return new RepositorySpace();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RepositorySpace }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.abiquo.com/ovfindex", name = "RepositorySpace")
    public JAXBElement<RepositorySpace> createRepositorySpace(RepositorySpace value)
    {
        return new JAXBElement<RepositorySpace>(_RepositorySpace_QNAME, RepositorySpace.class,
            null, value);
    }

}
