//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.25 at 04:38:05 PM CET 
//

package com.abiquo.ovfindex;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for OVFPackage complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;OVFPackage&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;attribute name=&quot;RepositoryURI&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anyURI&quot; /&gt;
 *       &lt;attribute name=&quot;OVFFile&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;OVFDescription&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;OVFIcon&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anyURI&quot; /&gt;
 *       &lt;attribute name=&quot;OVFCategory&quot;&gt;
 *         &lt;simpleType&gt;
 *           &lt;list itemType=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OVFPackage")
public class OVFPackage
{

    @XmlAttribute(name = "RepositoryURI", namespace = "http://www.abiquo.com/ovfindex", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String repositoryURI;

    @XmlAttribute(name = "OVFFile", namespace = "http://www.abiquo.com/ovfindex", required = true)
    protected String ovfFile;

    @XmlAttribute(name = "OVFDescription", namespace = "http://www.abiquo.com/ovfindex")
    protected String ovfDescription;

    @XmlAttribute(name = "OVFIcon", namespace = "http://www.abiquo.com/ovfindex")
    @XmlSchemaType(name = "anyURI")
    protected String ovfIcon;

    @XmlAttribute(name = "OVFCategory", namespace = "http://www.abiquo.com/ovfindex")
    protected List<String> ovfCategory;

    /**
     * Gets the value of the repositoryURI property.
     * 
     * @return possible object is {@link String }
     */
    public String getRepositoryURI()
    {
        return repositoryURI;
    }

    /**
     * Sets the value of the repositoryURI property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRepositoryURI(String value)
    {
        this.repositoryURI = value;
    }

    /**
     * Gets the value of the ovfFile property.
     * 
     * @return possible object is {@link String }
     */
    public String getOVFFile()
    {
        return ovfFile;
    }

    /**
     * Sets the value of the ovfFile property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setOVFFile(String value)
    {
        this.ovfFile = value;
    }

    /**
     * Gets the value of the ovfDescription property.
     * 
     * @return possible object is {@link String }
     */
    public String getOVFDescription()
    {
        return ovfDescription;
    }

    /**
     * Sets the value of the ovfDescription property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setOVFDescription(String value)
    {
        this.ovfDescription = value;
    }

    /**
     * Gets the value of the ovfIcon property.
     * 
     * @return possible object is {@link String }
     */
    public String getOVFIcon()
    {
        return ovfIcon;
    }

    /**
     * Sets the value of the ovfIcon property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setOVFIcon(String value)
    {
        this.ovfIcon = value;
    }

    /**
     * Gets the value of the ovfCategory property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the ovfCategory property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getOVFCategory().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     */
    public List<String> getOVFCategory()
    {
        if (ovfCategory == null)
        {
            ovfCategory = new ArrayList<String>();
        }
        return this.ovfCategory;
    }

}
