//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.25 at 04:38:05 PM CET 
//

package com.abiquo.ovfindex;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for RepositorySpace complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;RepositorySpace&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;OVFPackage&quot; type=&quot;{http://www.abiquo.com/ovfindex}OVFPackage&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;RepositoriURI&quot; use=&quot;required&quot; type=&quot;{http://www.abiquo.com/ovfindex}RepositoriURI&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RepositorySpace", propOrder = {"ovfPackage"})
public class RepositorySpace
{

    @XmlElement(name = "OVFPackage", required = true)
    protected List<OVFPackage> ovfPackage;

    @XmlAttribute(name = "RepositoriURI", namespace = "http://www.abiquo.com/ovfindex", required = true)
    protected String repositoriURI;

    /**
     * Gets the value of the ovfPackage property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the ovfPackage property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getOVFPackage().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link OVFPackage }
     */
    public List<OVFPackage> getOVFPackage()
    {
        if (ovfPackage == null)
        {
            ovfPackage = new ArrayList<OVFPackage>();
        }
        return this.ovfPackage;
    }

    /**
     * Gets the value of the repositoriURI property.
     * 
     * @return possible object is {@link String }
     */
    public String getRepositoriURI()
    {
        return repositoriURI;
    }

    /**
     * Sets the value of the repositoriURI property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRepositoriURI(String value)
    {
        this.repositoriURI = value;
    }

}
