/*
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in 
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an "AS IS" 
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 * 
 * The Original Code is available at http://www.abiquo.com/.....
 * 
 * The Initial Developer of the Original Code is Soluciones Grid, S.L. (www.abiquo.com),
 * Consell de Cent 296, Principal 2º, 08007 Barcelona, Spain.
 * 
 * No portions of the Code have been created by third parties. 
 * All Rights Reserved.
 * 
 * Contributor(s): ______________________________________.
 * 
 * Graphical User Interface of this software may be used under the terms
 * of the Common Public Attribution License Version 1.0 (the  "CPAL License", 
 * available at http://cpal.abiquo.com/), in which case the 
 * provisions of CPAL License are applicable instead of those above. In relation 
 * of this portions of the Code, a Legal Notice according to Exhibits A and B of 
 * CPAL Licence should be provided in any distribution of the corresponding Code 
 * to Graphical User Interface.
 */
package com.abiquo.abiserver.business.hibernate.pojohb.user;

import java.math.BigDecimal;

import com.abiquo.abiserver.business.hibernate.pojohb.IPojoHB;
import com.abiquo.abiserver.pojo.IPojo;
import com.abiquo.abiserver.pojo.user.Role;

// Generated 16-oct-2008 16:52:14 by Hibernate Tools 3.2.1.GA


/**
 * Role generated by hbm2java
 */
public class RoleHB implements java.io.Serializable, IPojoHB {

	private static final long serialVersionUID = -5172429643785560320L;
	
	private Integer idRole;
	private String shortDescription;
	private String largeDescription;
	private BigDecimal securityLevel;

	public RoleHB() {
	}

	public Integer getIdRole() {
		return this.idRole;
	}

	public void setIdRole(Integer idRole) {
		this.idRole = idRole;
	}

	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public String getLargeDescription() {
		return this.largeDescription;
	}

	public void setLargeDescription(String largeDescription) {
		this.largeDescription = largeDescription;
	}

	
	public BigDecimal getSecurityLevel() {
		return securityLevel;
	}

	public void setSecurityLevel(BigDecimal securityLevel) {
		this.securityLevel = securityLevel;
	}

	public IPojo toPojo() {
		Role role = new Role();
		
		role.setId(this.idRole);
		role.setShortDescription(this.shortDescription);
		role.setLargeDescription(this.largeDescription);
		role.setSecurityLevel(this.securityLevel);
		
		return role;
	}
}
