/*
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in 
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an "AS IS" 
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 * 
 * The Original Code is available at http://www.abiquo.com/.....
 * 
 * The Initial Developer of the Original Code is Soluciones Grid, S.L. (www.abiquo.com),
 * Consell de Cent 296, Principal 2º, 08007 Barcelona, Spain.
 * 
 * No portions of the Code have been created by third parties. 
 * All Rights Reserved.
 * 
 * Contributor(s): ______________________________________.
 * 
 * Graphical User Interface of this software may be used under the terms
 * of the Common Public Attribution License Version 1.0 (the  "CPAL License", 
 * available at http://cpal.abiquo.com/), in which case the 
 * provisions of CPAL License are applicable instead of those above. In relation 
 * of this portions of the Code, a Legal Notice according to Exhibits A and B of 
 * CPAL Licence should be provided in any distribution of the corresponding Code 
 * to Graphical User Interface.
 */
package com.abiquo.abiserver.business.hibernate.pojohb.user;

// Generated 16-oct-2008 16:52:14 by Hibernate Tools 3.2.1.GA

import java.util.Date;

import com.abiquo.abiserver.business.hibernate.pojohb.IPojoHB;
import com.abiquo.abiserver.pojo.IPojo;
import com.abiquo.abiserver.pojo.user.Enterprise;
import com.abiquo.abiserver.pojo.user.Role;
import com.abiquo.abiserver.pojo.user.User;

/**
 * User generated by hbm2java
 */
public class UserHB implements java.io.Serializable, IPojoHB
{

	private static final long serialVersionUID = 6655290980964418462L;
	
	private Integer idUser;
	private Integer userHBByIdUserCreation;
	private Integer userHBByIdUserLastModification;
	private RoleHB roleHB;
	private String user;
	private String name;
	private String surname;
	private String description;
	private String email;
	private String locale;
	private String password;
	private Date creationDate;
	private Date lastModificationDate;
	private Integer active;
	private Integer deleted;
	private EnterpriseHB enterpriseHB;


	public Integer getIdUser()
	{
		return this.idUser;
	}

	public void setIdUser(Integer idUser)
	{
		this.idUser = idUser;
	}

	public Integer getUserHBByIdUserCreation()
	{
		return this.userHBByIdUserCreation;
	}

	public void setUserHBByIdUserCreation(Integer userHBByIdUserCreation)
	{
		this.userHBByIdUserCreation = userHBByIdUserCreation;
	}

	public Integer getUserHBByIdUserLastModification()
	{
		return this.userHBByIdUserLastModification;
	}

	public void setUserHBByIdUserLastModification(Integer userHBByIdUserLstModification)
	{
		this.userHBByIdUserLastModification = userHBByIdUserLstModification;
	}

	public RoleHB getRoleHB()
	{
		return this.roleHB;
	}

	public void setRoleHB(RoleHB roleHB)
	{
		this.roleHB = roleHB;
	}

	public String getUser()
	{
		return this.user;
	}

	public void setUser(String user)
	{
		this.user = user;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getSurname()
	{
		return this.surname;
	}

	public void setSurname(String surname)
	{
		this.surname = surname;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getLocale()
	{
		return this.locale;
	}

	public void setLocale(String locale)
	{
		this.locale = locale;
	}

	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public Date getCreationDate()
	{
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate)
	{
		this.creationDate = creationDate;
	}

	public Date getLastModificationDate()
	{
		return this.lastModificationDate;
	}

	public void setLastModificationDate(Date lastModificationDate)
	{
		this.lastModificationDate = lastModificationDate;
	}

	public Integer getActive() {
		return active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}
	
	public Integer getDeleted() {
		return deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}
	
	public EnterpriseHB getEnterpriseHB() {
		return enterpriseHB;
	}

	public void setEnterpriseHB(EnterpriseHB enterpriseHB) {
		this.enterpriseHB = enterpriseHB;
	}

	public IPojo toPojo() 
	{
		User user = new User();
		
		user.setId(this.idUser);
		user.setRole((Role)this.roleHB.toPojo());
		user.setUser(this.user);
		user.setName(this.name);
		user.setSurname(this.surname);
		user.setDescription(this.description);
		user.setEmail(this.email);
		user.setPass(this.password);
		user.setActive(this.active == 1 ? true:false);
		user.setDeleted(this.deleted == 1 ? true:false);
		user.setLocale(this.locale);
		if(this.enterpriseHB != null)
			user.setEnterprise((Enterprise) this.enterpriseHB.toPojo());
		else
			user.setEnterprise(null);
		
		return user;
	}
	
	
	
}
