//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.25 at 04:38:05 PM CET 
//

package org.dmtf.schemas.ovf.envelope._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * User defined annotation on an entity
 * <p>
 * Java class for AnnotationSection_Type complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;AnnotationSection_Type&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://schemas.dmtf.org/ovf/envelope/1}Section_Type&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;Annotation&quot; type=&quot;{http://schemas.dmtf.org/ovf/envelope/1}Msg_Type&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotationSection_Type", propOrder = {"annotation"})
public class AnnotationSectionType extends SectionType
{

    @XmlElement(name = "Annotation", required = true)
    protected MsgType annotation;

    /**
     * Gets the value of the annotation property.
     * 
     * @return possible object is {@link MsgType }
     */
    public MsgType getAnnotation()
    {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value allowed object is {@link MsgType }
     */
    public void setAnnotation(MsgType value)
    {
        this.annotation = value;
    }

}
