//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.25 at 04:38:05 PM CET 
//

package org.dmtf.schemas.ovf.envelope._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Descriptions of virtual disks used within the package
 * <p>
 * Java class for DiskSection_Type complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;DiskSection_Type&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://schemas.dmtf.org/ovf/envelope/1}Section_Type&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;Disk&quot; type=&quot;{http://schemas.dmtf.org/ovf/envelope/1}VirtualDiskDesc_Type&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiskSection_Type", propOrder = {"disk"})
public class DiskSectionType extends SectionType
{

    @XmlElement(name = "Disk")
    protected List<VirtualDiskDescType> disk;

    /**
     * Gets the value of the disk property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the disk property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDisk().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link VirtualDiskDescType }
     */
    public List<VirtualDiskDescType> getDisk()
    {
        if (disk == null)
        {
            disk = new ArrayList<VirtualDiskDescType>();
        }
        return this.disk;
    }

}
