//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.25 at 04:38:05 PM CET 
//

package org.dmtf.schemas.ovf.envelope._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * Type for string resource bundle
 * <p>
 * Java class for Strings_Type complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;Strings_Type&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;Msg&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base=&quot;&lt;http://www.w3.org/2001/XMLSchema&gt;string&quot;&gt;
 *                 &lt;attribute name=&quot;msgid&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref=&quot;{http://www.w3.org/XML/1998/namespace}lang&quot;/&gt;
 *       &lt;attribute name=&quot;fileRef&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Strings_Type", propOrder = {"msg"})
public class StringsType
{

    @XmlElement(name = "Msg")
    protected List<StringsType.Msg> msg;

    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    @XmlAttribute(namespace = "http://schemas.dmtf.org/ovf/envelope/1")
    protected String fileRef;

    /**
     * Gets the value of the msg property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the msg property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getMsg().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link StringsType.Msg }
     */
    public List<StringsType.Msg> getMsg()
    {
        if (msg == null)
        {
            msg = new ArrayList<StringsType.Msg>();
        }
        return this.msg;
    }

    /**
     * Locale for this string resource bundle
     * 
     * @return possible object is {@link String }
     */
    public String getLang()
    {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setLang(String value)
    {
        this.lang = value;
    }

    /**
     * Gets the value of the fileRef property.
     * 
     * @return possible object is {@link String }
     */
    public String getFileRef()
    {
        return fileRef;
    }

    /**
     * Sets the value of the fileRef property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setFileRef(String value)
    {
        this.fileRef = value;
    }

    /**
     * String element value
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base=&quot;&lt;http://www.w3.org/2001/XMLSchema&gt;string&quot;&gt;
     *       &lt;attribute name=&quot;msgid&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"value"})
    public static class Msg
    {

        @XmlValue
        protected String value;

        @XmlAttribute(namespace = "http://schemas.dmtf.org/ovf/envelope/1", required = true)
        protected String msgid;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         */
        public String getValue()
        {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setValue(String value)
        {
            this.value = value;
        }

        /**
         * Gets the value of the msgid property.
         * 
         * @return possible object is {@link String }
         */
        public String getMsgid()
        {
            return msgid;
        }

        /**
         * Sets the value of the msgid property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setMsgid(String value)
        {
            this.msgid = value;
        }

    }

}
