//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.25 at 04:38:05 PM CET 
//

package org.dmtf.schemas.ovf.envelope._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Specifies virtual hardware requirements for a virtual machine
 * <p>
 * Java class for VirtualHardwareSection_Type complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;VirtualHardwareSection_Type&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://schemas.dmtf.org/ovf/envelope/1}Section_Type&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;System&quot; type=&quot;{http://schemas.dmtf.org/ovf/envelope/1}VSSD_Type&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;Item&quot; type=&quot;{http://schemas.dmtf.org/ovf/envelope/1}RASD_Type&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;transport&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; default=&quot;&quot; /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VirtualHardwareSection_Type", propOrder = {"system", "item"})
public class VirtualHardwareSectionType extends SectionType
{

    @XmlElement(name = "System")
    protected VSSDType system;

    @XmlElement(name = "Item")
    protected List<RASDType> item;

    @XmlAttribute(namespace = "http://schemas.dmtf.org/ovf/envelope/1")
    protected String transport;

    /**
     * Gets the value of the system property.
     * 
     * @return possible object is {@link VSSDType }
     */
    public VSSDType getSystem()
    {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value allowed object is {@link VSSDType }
     */
    public void setSystem(VSSDType value)
    {
        this.system = value;
    }

    /**
     * Gets the value of the item property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the item property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getItem().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link RASDType }
     */
    public List<RASDType> getItem()
    {
        if (item == null)
        {
            item = new ArrayList<RASDType>();
        }
        return this.item;
    }

    /**
     * Gets the value of the transport property.
     * 
     * @return possible object is {@link String }
     */
    public String getTransport()
    {
        if (transport == null)
        {
            return "";
        }
        else
        {
            return transport;
        }
    }

    /**
     * Sets the value of the transport property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTransport(String value)
    {
        this.transport = value;
    }

}
