//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.25 at 04:38:05 PM CET 
//

package org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_virtualsystemsettingdata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.dmtf.schemas.wbem.wscim._1.common.CimString;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_virtualsystemsettingdata
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory
{

    private final static QName _VirtualSystemType_QNAME =
        new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData",
            "VirtualSystemType");

    private final static QName _Caption_QNAME =
        new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData",
            "Caption");

    private final static QName _CIMVirtualSystemSettingData_QNAME =
        new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData",
            "CIM_VirtualSystemSettingData");

    private final static QName _InstanceId_QNAME =
        new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData",
            "InstanceId");

    private final static QName _VirtualSystemIdentifier_QNAME =
        new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData",
            "VirtualSystemIdentifier");

    private final static QName _Description_QNAME =
        new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData",
            "Description");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes
     * for package: org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_virtualsystemsettingdata
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link CIMVirtualSystemSettingDataType }
     */
    public CIMVirtualSystemSettingDataType createCIMVirtualSystemSettingDataType()
    {
        return new CIMVirtualSystemSettingDataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "VirtualSystemType")
    public JAXBElement<CimString> createVirtualSystemType(CimString value)
    {
        return new JAXBElement<CimString>(_VirtualSystemType_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "Caption")
    public JAXBElement<CimString> createCaption(CimString value)
    {
        return new JAXBElement<CimString>(_Caption_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIMVirtualSystemSettingDataType }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "CIM_VirtualSystemSettingData")
    public JAXBElement<CIMVirtualSystemSettingDataType> createCIMVirtualSystemSettingData(
        CIMVirtualSystemSettingDataType value)
    {
        return new JAXBElement<CIMVirtualSystemSettingDataType>(_CIMVirtualSystemSettingData_QNAME,
            CIMVirtualSystemSettingDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "InstanceId")
    public JAXBElement<CimString> createInstanceId(CimString value)
    {
        return new JAXBElement<CimString>(_InstanceId_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "VirtualSystemIdentifier")
    public JAXBElement<CimString> createVirtualSystemIdentifier(CimString value)
    {
        return new JAXBElement<CimString>(_VirtualSystemIdentifier_QNAME, CimString.class, null,
            value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "Description")
    public JAXBElement<CimString> createDescription(CimString value)
    {
        return new JAXBElement<CimString>(_Description_QNAME, CimString.class, null, value);
    }

}
