/*
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in 
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an "AS IS" 
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 * 
 * The Original Code is available at http://www.abiquo.com/.....
 * 
 * The Initial Developer of the Original Code is Soluciones Grid, S.L. (www.abiquo.com),
 * Consell de Cent 296, Principal 2º, 08007 Barcelona, Spain.
 * 
 * No portions of the Code have been created by third parties. 
 * All Rights Reserved.
 * 
 * Contributor(s): ______________________________________.
 * 
 * Graphical User Interface of this software may be used under the terms
 * of the Common Public Attribution License Version 1.0 (the  "CPAL License", 
 * available at http://cpal.abiquo.com/), in which case the 
 * provisions of CPAL License are applicable instead of those above. In relation 
 * of this portions of the Code, a Legal Notice according to Exhibits A and B of 
 * CPAL Licence should be provided in any distribution of the corresponding Code 
 * to Graphical User Interface.
 */
package com.abiquo.abiserver.business.hibernate.pojohb.virtualappliance;

// Generated 16-oct-2008 16:52:14 by Hibernate Tools 3.2.1.GA

import com.abiquo.abiserver.business.hibernate.pojohb.IPojoHB;
import com.abiquo.abiserver.pojo.IPojo;
import com.abiquo.abiserver.pojo.virtualappliance.Node;
import com.abiquo.abiserver.pojo.virtualappliance.NodeType;

/**
 * Nodes generated by hbm2java
 */
public class NodeHB implements java.io.Serializable, IPojoHB {

	private static final long serialVersionUID = 8658661577766502632L;
	
	protected int idNode;
	protected String name;
	protected int idVirtualApp;
	protected NodeTypeHB nodeTypeHB;
	
	protected int posX;
	protected int posY;

	public int getIdNode() {
		return idNode;
	}

	public void setIdNode(int idNode) {
		this.idNode = idNode;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getIdVirtualApp() {
		return idVirtualApp;
	}

	public void setIdVirtualApp(int idVirtualApp) {
		this.idVirtualApp = idVirtualApp;
	}

	public NodeTypeHB getNodeTypeHB() {
		return nodeTypeHB;
	}

	public void setNodeTypeHB(NodeTypeHB nodeTypeHB) {
		this.nodeTypeHB = nodeTypeHB;
	}

	public int getPosX() {
		return posX;
	}

	public void setPosX(int posX) {
		this.posX = posX;
	}

	public int getPosY() {
		return posY;
	}

	public void setPosY(int posY) {
		this.posY = posY;
	}

	public IPojo toPojo()
	{
		Node node = new Node();
		node.setId(this.idNode);
		node.setIdVirtualAppliance(this.idVirtualApp);
		node.setName(this.name);
		node.setNodeType((NodeType) this.nodeTypeHB.toPojo());
		
		node.setPosX(this.posX);
		node.setPosY(this.posY);
		
		return node;
	}
}
