/*
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in 
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an "AS IS" 
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 * 
 * The Original Code is available at http://www.abiquo.com/.....
 * 
 * The Initial Developer of the Original Code is Soluciones Grid, S.L. (www.abiquo.com),
 * Consell de Cent 296, Principal 2º, 08007 Barcelona, Spain.
 * 
 * No portions of the Code have been created by third parties. 
 * All Rights Reserved.
 * 
 * Contributor(s): ______________________________________.
 * 
 * Graphical User Interface of this software may be used under the terms
 * of the Common Public Attribution License Version 1.0 (the  "CPAL License", 
 * available at http://cpal.abiquo.com/), in which case the 
 * provisions of CPAL License are applicable instead of those above. In relation 
 * of this portions of the Code, a Legal Notice according to Exhibits A and B of 
 * CPAL Licence should be provided in any distribution of the corresponding Code 
 * to Graphical User Interface.
 */
package com.abiquo.abiserver.business.hibernate.pojohb.infrastructure;

// Generated 16-oct-2008 16:52:14 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.abiquo.abiserver.business.hibernate.pojohb.IPojoHB;
import com.abiquo.abiserver.business.hibernate.pojohb.user.UserHB;
import com.abiquo.abiserver.pojo.IPojo;
import com.abiquo.abiserver.pojo.infrastructure.HyperVisor;
import com.abiquo.abiserver.pojo.infrastructure.HyperVisorType;
import com.abiquo.abiserver.pojo.infrastructure.PhysicalMachine;

/**
 * Hypervisor generated by hbm2java
 */
public class HypervisorHB implements java.io.Serializable, IPojoHB
{

	private static final long serialVersionUID = -7337606409880143290L;
	
	private Integer idHyper;
	private String shortDescription;
	private Set<VirtualmachineHB> virtualmachines = new HashSet<VirtualmachineHB>(0);

	private String ip;
	private Integer port;
	private PhysicalmachineHB physicalMachine;
	private HypervisorTypeHB type;

	
	private UserHB userHBByIdUserCreation;
	private UserHB userHBByIdUserLastModification;
	
	private Date creationDate;
	private Date lastModificationDate;
	
	public HypervisorHB()
	{
	}

	public HypervisorHB(String shortDescription)
	{
		this.shortDescription = shortDescription;
	}

	public Integer getIdHyper()
	{
		return this.idHyper;
	}

	public void setIdHyper(Integer idHyper)
	{
		this.idHyper = idHyper;
	}

	public String getShortDescription()
	{
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription)
	{
		this.shortDescription = shortDescription;
	}

	public Set<VirtualmachineHB> getVirtualmachines()
	{
		return this.virtualmachines;
	}

	public void setVirtualmachines(Set<VirtualmachineHB> virtualmachines)
	{
		this.virtualmachines = virtualmachines;
	}

	public String getIp()
	{
		return ip;
	}

	public void setIp(String ip)
	{
		this.ip = ip;
	}

	public Integer getPort()
	{
		return port;
	}

	public void setPort(Integer port)
	{
		this.port = port;
	}

	public HypervisorTypeHB getType()
	{
		return type;
	}

	public void setType(HypervisorTypeHB type)
	{
		this.type = type;
	}

	public PhysicalmachineHB getPhysicalMachine()
	{
		return physicalMachine;
	}

	public void setPhysicalMachine(PhysicalmachineHB physicalMachine)
	{
		this.physicalMachine = physicalMachine;
	}

	public UserHB getUserHBByIdUserCreation() {
		return userHBByIdUserCreation;
	}

	public void setUserHBByIdUserCreation(UserHB userHBByIdUserCreation) {
		this.userHBByIdUserCreation = userHBByIdUserCreation;
	}

	public UserHB getUserHBByIdUserLastModification() {
		return userHBByIdUserLastModification;
	}

	public void setUserHBByIdUserLastModification(
			UserHB userHBByIdUserLastModification) {
		this.userHBByIdUserLastModification = userHBByIdUserLastModification;
	}

	public Date getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastModificationDate() {
		return lastModificationDate;
	}

	public void setLastModificationDate(Date lastModificationDate) {
		this.lastModificationDate = lastModificationDate;
	}
	
	public IPojo toPojo()
	{
		HyperVisor hyperVisor = new HyperVisor();
		
		hyperVisor.setId(this.idHyper);
		hyperVisor.setName(this.getType().getName());
		hyperVisor.setAssignedTo((PhysicalMachine) this.physicalMachine.toPojo());
		
		hyperVisor.setShortDescription(this.shortDescription);
		hyperVisor.setIp(this.ip);
		hyperVisor.setPort(this.port);
		
		hyperVisor.setType((HyperVisorType) this.type.toPojo());
		
		return hyperVisor;
	}
}
