/*
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in 
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an "AS IS" 
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 * 
 * The Original Code is available at http://www.abiquo.com/.....
 * 
 * The Initial Developer of the Original Code is Soluciones Grid, S.L. (www.abiquo.com),
 * Consell de Cent 296, Principal 2º, 08007 Barcelona, Spain.
 * 
 * No portions of the Code have been created by third parties. 
 * All Rights Reserved.
 * 
 * Contributor(s): ______________________________________.
 * 
 * Graphical User Interface of this software may be used under the terms
 * of the Common Public Attribution License Version 1.0 (the  "CPAL License", 
 * available at http://cpal.abiquo.com/), in which case the 
 * provisions of CPAL License are applicable instead of those above. In relation 
 * of this portions of the Code, a Legal Notice according to Exhibits A and B of 
 * CPAL Licence should be provided in any distribution of the corresponding Code 
 * to Graphical User Interface.
 */
package com.abiquo.abiserver.business.hibernate.pojohb.infrastructure;

// Generated 16-oct-2008 16:52:14 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.abiquo.abiserver.business.hibernate.pojohb.IPojoHB;
import com.abiquo.abiserver.business.hibernate.pojohb.user.UserHB;
import com.abiquo.abiserver.pojo.IPojo;
import com.abiquo.abiserver.pojo.infrastructure.DataCenter;
import com.abiquo.abiserver.pojo.infrastructure.Rack;

/**
 * Rack generated by hbm2java
 */
public class RackHB implements java.io.Serializable, IPojoHB {
	
	private static final long serialVersionUID = 6425447787740392277L;
	
	private Integer idRack;
	private UserHB userHBByIdUserLastModification;
	private DatacenterHB datacenter;
	private UserHB userHBByIdUserCreataion;
	private String name;
	private String shortDescription;
	private String largeDescription;
	private Date creatioNdate;
	private Date lastModificationDate;
	private Set<PhysicalmachineHB> physicalmachines = new HashSet<PhysicalmachineHB>(0);

	public RackHB() {
	}

	public RackHB(DatacenterHB datacenter, UserHB userHBByIdUserCreataion, String name,
			Date creatioNdate) {
		this.datacenter = datacenter;
		this.userHBByIdUserCreataion = userHBByIdUserCreataion;
		this.name = name;
		this.creatioNdate = creatioNdate;
	}

	public RackHB(UserHB userHBByIdUserLastModification, DatacenterHB datacenter,
			UserHB userHBByIdUserCreataion, String name, String shortDescription,
			String largeDescription, Date creatioNdate,
			Date lastModificationDate, Set<PhysicalmachineHB> physicalmachines) {
		this.userHBByIdUserLastModification = userHBByIdUserLastModification;
		this.datacenter = datacenter;
		this.userHBByIdUserCreataion = userHBByIdUserCreataion;
		this.name = name;
		this.shortDescription = shortDescription;
		this.largeDescription = largeDescription;
		this.creatioNdate = creatioNdate;
		this.lastModificationDate = lastModificationDate;
		this.physicalmachines = physicalmachines;
	}

	public Integer getIdRack() {
		return this.idRack;
	}

	public void setIdRack(Integer idRack) {
		this.idRack = idRack;
	}

	public UserHB getUserHBByIdUserLastModification() {
		return this.userHBByIdUserLastModification;
	}

	public void setUserHBByIdUserLastModification(
			UserHB userHBByIdUserLastModification) {
		this.userHBByIdUserLastModification = userHBByIdUserLastModification;
	}

	public DatacenterHB getDatacenter() {
		return this.datacenter;
	}

	public void setDatacenter(DatacenterHB datacenter) {
		this.datacenter = datacenter;
	}

	public UserHB getUserHBByIdUserCreataion() {
		return this.userHBByIdUserCreataion;
	}

	public void setUserHBByIdUserCreataion(UserHB userHBByIdUserCreataion) {
		this.userHBByIdUserCreataion = userHBByIdUserCreataion;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public String getLargeDescription() {
		return this.largeDescription;
	}

	public void setLargeDescription(String largeDescription) {
		this.largeDescription = largeDescription;
	}

	public Date getCreatioNdate() {
		return this.creatioNdate;
	}

	public void setCreatioNdate(Date creatioNdate) {
		this.creatioNdate = creatioNdate;
	}

	public Date getLastModificationDate() {
		return this.lastModificationDate;
	}

	public void setLastModificationDate(Date lastModificationDate) {
		this.lastModificationDate = lastModificationDate;
	}

	public Set<PhysicalmachineHB> getPhysicalmachines() {
		return this.physicalmachines;
	}

	public void setPhysicalmachines(Set<PhysicalmachineHB> physicalmachines) {
		this.physicalmachines = physicalmachines;
	}

	public IPojo toPojo()
	{
		Rack rack = new Rack();
		rack.setDataCenter((DataCenter)this.datacenter.toPojo());
		rack.setId(this.idRack);
		rack.setLargeDescription(this.largeDescription);
		rack.setName(this.name);
		rack.setShortDescription(this.shortDescription);
		return rack;
	}

}
